# Generated by Django 5.0.3 on 2024-06-09 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pri3', '0005_remove_creativewritingscores_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abacusscores',
            name='title',
        ),
    ]
