# Generated by Django 5.0.3 on 2024-06-08 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pri4', '0005_remove_abacusscores_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abacusscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='agriculturalsciencescores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='basicscitechscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='civiceducationscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='computerstudiesscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='creativeartsscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='creativewritingscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='crkscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='englishliteraturescores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='englishscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='historyscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='mathematicsscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='musicscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='phescores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='quantitativereasoningscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='socialstudiesscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='spellingsscores',
            old_name='student',
            new_name='pupil',
        ),
        migrations.RenameField(
            model_name='verbalreasoningscores',
            old_name='student',
            new_name='pupil',
        ),
    ]
