# Generated by Django 5.0.3 on 2024-06-09 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pri4', '0008_alter_abacusscores_pupil_and_more'),
        ('pupilbase', '0002_pupil_address_pupil_classlevel_pupil_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abacusscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='agriculturalsciencescores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='basicscitechscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='civiceducationscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='computerstudiesscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='creativeartsscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='creativewritingscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='crkscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='englishliteraturescores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='englishscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='historyscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='musicscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='phescores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='quantitativereasoningscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='socialstudiesscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='spellingsscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
        migrations.AlterField(
            model_name='verbalreasoningscores',
            name='pupil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pupilbase.pupil', verbose_name='Pupil'),
        ),
    ]
