# Generated by Django 5.0.3 on 2024-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, default='firstname', max_length=256, null=True)),
                ('middlename', models.CharField(blank=True, default='middlename', max_length=256, null=True)),
                ('surname', models.CharField(blank=True, default='surname', max_length=256, null=True)),
            ],
        ),
    ]
