# Generated by Django 5.0.3 on 2024-06-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupilbase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='address',
            field=models.CharField(blank=True, default='null', max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='pupil',
            name='classlevel',
            field=models.CharField(choices=[('Primary 5', 'Primary 5'), ('Primary 4', 'Primary 4'), ('Primary 3', 'Primary 3'), ('Primary 2', 'Primary 2'), ('Primary 1', 'Primary 1'), ('Nursery 2', 'Nursery 2'), ('Nursery 1', 'Nursery 1'), ('Pre-nursery', 'Pre-nursery'), ('Creche', 'Creche')], default='Primary 5', max_length=50),
        ),
        migrations.AddField(
            model_name='pupil',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Null', 'Null')], default='Null', max_length=50),
        ),
    ]
